name = "QuantumComputationalComplexityModel"
uuid = "123e4567-e89b-12d3-a456-426614174000" # You can generate a new UUID if desired
authors = ["San"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
